version: "3"

services:
  Starter_postgresql:
    image: postgres:12
    container_name: Starter_postgresql
    volumes:
      - Starter_postgresql:/var/lib/postgreslq/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - Starter_network

volumes:
  Starter_postgresql:
    external: true
networks:
  Starter_network:
    external: true
    